import "./globals.css";
import { DM_Sans, Pixelify_Sans } from "next/font/google";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
});

const pixelifySans = Pixelify_Sans({
  subsets: ["latin"],
  weight: ["400"],
});



export const metadata = {
  title: "Lunaria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${dmSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
