import { DM_Sans, Pixelify_Sans } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css' 

const fontCaslon = localFont({
  src: './fonts/Calora.woff2',
  display: 'swap',
  variable: '--font-caslon',
})

const fontDM = DM_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-dm',
})

const fontPixel = Pixelify_Sans({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-pixel',
})


export const metadata = {

  title: "Lunaria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${fontCaslon.variable} ${fontDM.variable} ${fontPixel.variable}`}
      >
        {children}
      </body>
    </html>
  )
}